# Generated by Django 4.2.5 on 2023-09-06 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LectureType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typename', models.CharField(max_length=30)),
                ('name', models.CharField(choices=[(1, '코딩'), (2, '시스템'), (3, '프로젝트'), (4, '팀플')], default=1, max_length=20)),
                ('subject', models.BooleanField(choices=[(True, '교과'), (False, '비교과')])),
                ('env', models.BinaryField(max_length=4, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semestername', models.CharField(max_length=30)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=30)),
                ('nickname', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=10)),
                ('number', models.CharField(max_length=30)),
                ('gittoken', models.CharField(max_length=30, null=True)),
                ('department', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=255, null=True)),
                ('year', models.IntegerField()),
                ('create_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SWLAB.user')),
            ],
        ),
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isallow', models.BooleanField(default=False)),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SWLAB.lecture')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SWLAB.user')),
            ],
        ),
    ]
