# Generated by Django 4.2.5 on 2023-09-06 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SWLAB', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecturetype',
            name='typename',
        ),
    ]
